// Code generated by counterfeiter. DO NOT EDIT.
package servicesfakes

import (
	"sync"

	"github.com/ancarebeca/expense-tracker/model"
	"github.com/ancarebeca/expense-tracker/services"
)

type FakeParser struct {
	ParseStub        func(data [][]string) ([]*model.Statement, error)
	parseMutex       sync.RWMutex
	parseArgsForCall []struct {
		data [][]string
	}
	parseReturns struct {
		result1 []*model.Statement
		result2 error
	}
	parseReturnsOnCall map[int]struct {
		result1 []*model.Statement
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeParser) Parse(data [][]string) ([]*model.Statement, error) {
	var dataCopy [][]string
	if data != nil {
		dataCopy = make([][]string, len(data))
		copy(dataCopy, data)
	}
	fake.parseMutex.Lock()
	ret, specificReturn := fake.parseReturnsOnCall[len(fake.parseArgsForCall)]
	fake.parseArgsForCall = append(fake.parseArgsForCall, struct {
		data [][]string
	}{dataCopy})
	fake.recordInvocation("Parse", []interface{}{dataCopy})
	fake.parseMutex.Unlock()
	if fake.ParseStub != nil {
		return fake.ParseStub(data)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.parseReturns.result1, fake.parseReturns.result2
}

func (fake *FakeParser) ParseCallCount() int {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return len(fake.parseArgsForCall)
}

func (fake *FakeParser) ParseArgsForCall(i int) [][]string {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return fake.parseArgsForCall[i].data
}

func (fake *FakeParser) ParseReturns(result1 []*model.Statement, result2 error) {
	fake.ParseStub = nil
	fake.parseReturns = struct {
		result1 []*model.Statement
		result2 error
	}{result1, result2}
}

func (fake *FakeParser) ParseReturnsOnCall(i int, result1 []*model.Statement, result2 error) {
	fake.ParseStub = nil
	if fake.parseReturnsOnCall == nil {
		fake.parseReturnsOnCall = make(map[int]struct {
			result1 []*model.Statement
			result2 error
		})
	}
	fake.parseReturnsOnCall[i] = struct {
		result1 []*model.Statement
		result2 error
	}{result1, result2}
}

func (fake *FakeParser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeParser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ services.Parser = new(FakeParser)
